### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by piyush9290** [ayushn21/AvatarImageView#14]
Hello Ayush,

I have updated my code to swift 3.0 but when I try to run, it gives me an legacy swift version error.
Later when I convert the dependency code, it gives me so many errors. Could you please check if the it is working or not?

![screen shot 2016-09-20 at 4 37 09 pm](https://cloud.githubusercontent.com/assets/17264408/18688004/8a5e0546-7f50-11e6-9c8c-e9c9ff6774dc.png)

**Comment by ayushn21** [comment]
Hi Piyush,

This looks like an issue with your project. Please go to the project's build settings and set the "Use Legacy Swift Language Version" setting to "No".

<img width="625" alt="screen shot 2016-09-20 at 9 42 51 pm" src="https://cloud.githubusercontent.com/assets/4924039/18688225/3edcf3ea-7f7b-11e6-9b5d-a681bbd50634.png">

If you would like to use Swift 3 with this library, please don't convert the code yourself as it was not a trivial migration. Version 2.0.1 of the library is Swift 3 and available through CocoaPods, please use this version and you shouldn't have any trouble.

Let me know if you have any more problems!

Thanks,
Ayush

**Comment by piyush9290** [comment]
Hello,

I have changed the  project settings as you said but issue is still there.

Thanks,
Piyush

**Comment by ayushn21** [comment]
Ah, strange. Could you describe your project setup a bit please? Are you using CocoaPods? If you are, is this error in the "Pods" project or your main project?

**Comment by piyush9290** [comment]
I'm using CocoaPods. The error is in Pods projects.

![screen shot 2016-09-20 at 5 16 44 pm](https://cloud.githubusercontent.com/assets/17264408/18689280/54444cd0-7f56-11e6-84e7-c92fccb1d5f9.png)
![screen shot 2016-09-20 at 5 16 54 pm](https://cloud.githubusercontent.com/assets/17264408/18689281/544b783e-7f56-11e6-8d6f-7e604e544b11.png)
![screen shot 2016-09-20 at 5 17 13 pm](https://cloud.githubusercontent.com/assets/17264408/18689283/544fee46-7f56-11e6-979b-50b9417d7418.png)
![screen shot 2016-09-20 at 5 18 43 pm](https://cloud.githubusercontent.com/assets/17264408/18689282/544d3642-7f56-11e6-92b4-311be5a8bf2a.png)

**Comment by ayushn21** [comment]
Ah I see, thanks for the screenshots. I've integrated the library using CocoaPods (as seen in the example project) so it does work. Could you tell me which version of CocoaPods you're using please? I know there are issues with Xcode 8 on older versions. Just run `pod --version` on Terminal.

**Comment by ayushn21** [comment]
Also could you please verify whether the Legacy Swift build setting is correct on the AvatarImageView target on the Pods project?

<img width="835" alt="screen shot 2016-09-20 at 10 24 57 pm" src="https://cloud.githubusercontent.com/assets/4924039/18689467/2439028a-7f81-11e6-85cd-e892309f0c45.png">

**Comment by piyush9290** [comment]
Yeah, AvatarImageView has "Use Legacy Swift Language Version" as Unspecified. Now it's working.
Thank You Ayush

**Comment by drinkius** [comment]
Same problem here, by default the pod was installed with "Unspecified" legacy setting. I think it should be fixed in the pod specification somewhere

**Comment by ayushn21** [comment]
@drinkius,

A workaround can be specified in the Podfile, can't do anything in the podspec unfortunately :(

https://github.com/CocoaPods/CocoaPods/issues/5521
