### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by ghost** [ayushn21/AvatarImageView#18]
Plans to migrate the code to Swift 4?

**Comment by loryhuz** [comment]
I opened a pull request. For the moment you can sync the swift-4 branch on my fork:
pod "AvatarImageView", :git => 'https://github.com/loryhuz/AvatarImageView.git', :branch => 'swift-4'

**Comment by ayushn21** [comment]
Sorry, completely missed this issue somehow! @csimmonsbluebook thanks for the PR. I'll take a quick look and merge as soon as I get a chance!

**Comment by ghost** [comment]
@ayushn21 Credit goes to @loryhuz! I'm just along for the ride :)

**Comment by ayushn21** [comment]
Ah yes indeed. Didn't really read the thread properly! Cheers @loryhuz just taking a look now and will merge and push a new release to cocoapods

**Comment by ayushn21** [comment]
v2.1.1 with Swift 4 support now available through CocoaPods 👍
