### ISSUE TITLE
Border on Avatar view?

### ISSUE THREAD

**Issue by neodave** [ayushn21/AvatarImageView#25]
Do you have a suggestion of how we could add a border to the Avatar view? I don't see that as a current option. Looks great otherwise and could be very useful. Thanks for the code...

**Comment by ayushn21** [comment]
Hey ... you should be able to add a border using the `layer.borderWidth` property on the view. I don't see any reason why that wouldn't work.

**Comment by neodave** [comment]
Thank you. We actually did go ahead and implement it that way. Great solution, and we are using it in our app. So thanks for the code :)

**Comment by ayushn21** [comment]
You're welcome. Glad to hear you've found it helpful! :)
